// PM2 Production Config for Mempool
// - envConfig: general config from .env.prod (dotenv format)
// - secrets: sensitive data from JS file (not committed to git)
const dotenv = require('dotenv');
const path = require('path');
const fs = require('fs');

const BASE_DIR = process.env.MEMPOOL_BASE_DIR || '/home/opcat/mempool';
const BACKEND_DIR = path.join(BASE_DIR, 'backend');
const FRONTEND_DIR = path.join(BASE_DIR, 'frontend');

// Load non-sensitive environment variables
const envConfig = dotenv.config({ path: path.join(BASE_DIR, '.env.prod') }).parsed || {};

// Load sensitive secrets (generated by fetch-secrets.sh)
let secrets = {};
try {
  secrets = require(path.join(BASE_DIR, 'secrets.js'));
} catch (e) {
  console.warn('⚠️  secrets.js not found, trying environment variables');
  // Fallback to environment variables
  secrets = {
    CORE_RPC_PASSWORD: process.env.CORE_RPC_PASSWORD,
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  };
}

// Generate mempool-config.json
function generateMempoolConfig(envConfig, secrets) {
  return {
    "MEMPOOL": {
      "OFFICIAL": false,
      "NETWORK": envConfig.MEMPOOL_NETWORK || "mainnet",
      "BACKEND": "electrum",
      "ENABLED": true,
      "HTTP_PORT": parseInt(envConfig.BACKEND_PORT) || 8999,
      "SPAWN_CLUSTER_PROCS": 0,
      "API_URL_PREFIX": "/api/v1/",
      "POLL_RATE_MS": 2000,
      "CACHE_DIR": "./cache",
      "CACHE_ENABLED": true,
      "CLEAR_PROTECTION_MINUTES": 20,
      "RECOMMENDED_FEE_PERCENTILE": 50,
      "BLOCK_WEIGHT_UNITS": 32000000,
      "INITIAL_BLOCKS_AMOUNT": 8,
      "MEMPOOL_BLOCKS_AMOUNT": 8,
      "INDEXING_BLOCKS_AMOUNT": 11000,
      "BLOCKS_SUMMARIES_INDEXING": true,
      "GOGGLES_INDEXING": false,
      "USE_SECOND_NODE_FOR_MINFEE": false,
      "EXTERNAL_ASSETS": [],
      "EXTERNAL_MAX_RETRY": 1,
      "EXTERNAL_RETRY_INTERVAL": 0,
      "USER_AGENT": "mempool",
      "STDOUT_LOG_MIN_PRIORITY": "debug",
      "AUTOMATIC_POOLS_UPDATE": false,
      "POOLS_JSON_URL": "https://raw.githubusercontent.com/mempool/mining-pools/master/pools-v2.json",
      "POOLS_JSON_TREE_URL": "https://api.github.com/repos/mempool/mining-pools/git/trees/master",
      "POOLS_UPDATE_DELAY": 604800,
      "AUDIT": false,
      "RUST_GBT": true,
      "LIMIT_GBT": false,
      "CPFP_INDEXING": false,
      "DISK_CACHE_BLOCK_INTERVAL": 6,
      "MAX_PUSH_TX_SIZE_WEIGHT": 4000000,
      "ALLOW_UNREACHABLE": true,
      "PRICE_UPDATES_PER_HOUR": 1,
      "MAX_TRACKED_ADDRESSES": 100,
      "UNIX_SOCKET_PATH": ""
    },
    "CORE_RPC": {
      "HOST": envConfig.CORE_RPC_HOST || "127.0.0.1",
      "PORT": parseInt(envConfig.CORE_RPC_PORT) || 8332,
      "USERNAME": envConfig.CORE_RPC_USERNAME || "mempool",
      "PASSWORD": secrets.CORE_RPC_PASSWORD || "mempool",
      "TIMEOUT": 60000,
      "COOKIE": false,
      "COOKIE_PATH": "",
      "DEBUG_LOG_PATH": ""
    },
    "ELECTRUM": {
      "HOST": envConfig.ELECTRUM_HOST || "0.0.0.0",
      "PORT": parseInt(envConfig.ELECTRUM_PORT) || 50006,
      "TLS_ENABLED": envConfig.ELECTRUM_TLS_ENABLED === 'true' || false
    },
    "ESPLORA": {
      "REST_API_URL": envConfig.ELECTRS_API || "http://127.0.0.1:3006",
      "BATCH_QUERY_BASE_SIZE": 1000,
      "RETRY_UNIX_SOCKET_AFTER": 30000,
      "REQUEST_TIMEOUT": 300000,
      "FALLBACK_TIMEOUT": 5000,
      "FALLBACK": [],
      "MAX_BEHIND_TIP": 2
    },
    "DATABASE": {
      "ENABLED": true,
      "HOST": envConfig.DATABASE_HOST || "127.0.0.1",
      "SOCKET": "",
      "PORT": parseInt(envConfig.DATABASE_PORT) || 3306,
      "DATABASE": envConfig.DATABASE_NAME || "mempool",
      "USERNAME": envConfig.DATABASE_USERNAME || "mempool",
      "PASSWORD": secrets.DATABASE_PASSWORD || "mempool",
      "TIMEOUT": 180000,
      "PID_DIR": "",
      "POOL_SIZE": 10,
      "SSL": envConfig.DATABASE_SSL === 'true' || false,
      "SSL_REJECT_UNAUTHORIZED": envConfig.DATABASE_SSL_REJECT_UNAUTHORIZED === 'false' ? false : true
    },
    "SYSLOG": {
      "ENABLED": false,
      "HOST": "127.0.0.1",
      "PORT": 514,
      "MIN_PRIORITY": "info",
      "FACILITY": "local7"
    },
    "STATISTICS": {
      "ENABLED": true,
      "TX_PER_SECOND_SAMPLE_PERIOD": 150
    },
    "LIGHTNING": {
      "ENABLED": false,
      "BACKEND": "lnd",
      "STATS_REFRESH_INTERVAL": 600,
      "GRAPH_REFRESH_INTERVAL": 600,
      "LOGGER_UPDATE_INTERVAL": 30,
      "RUST_GBTUPDATE_INTERVAL": 30,
      "FORENSICS_INTERVAL": 43200,
      "FORENSICS_RATE_LIMIT": 20
    },
    "LND": {
      "TLS_CERT_PATH": "tls.cert",
      "MACAROON_PATH": "readonly.macaroon",
      "REST_API_URL": "https://localhost:8080",
      "TIMEOUT": 10000
    },
    "CLIGHTNING": {
      "SOCKET": "lightning-rpc"
    },
    "SOCKS5PROXY": {
      "ENABLED": false,
      "USE_ONION": true,
      "HOST": "127.0.0.1",
      "PORT": 9050,
      "USERNAME": "",
      "PASSWORD": ""
    },
    "EXTERNAL_DATA_SERVER": {
      "MEMPOOL_API": "https://mempool.space/api/v1",
      "MEMPOOL_ONION": "http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/v1",
      "LIQUID_API": "https://liquid.network/api/v1",
      "LIQUID_ONION": "http://liquidmom47f6s3m53ebfxn47p76a6tlnxib3wp6deux7wuzotdr6cyd.onion/api/v1"
    },
    "REDIS": {
      "ENABLED": false,
      "UNIX_SOCKET_PATH": "/tmp/redis.sock",
      "BATCH_QUERY_BASE_SIZE": 5000
    },
    "REPLICATION": {
      "ENABLED": false,
      "AUDIT": false,
      "AUDIT_START_HEIGHT": 774000,
      "STATISTICS": false,
      "STATISTICS_START_TIME": 1481932800,
      "SERVERS": [
        "list",
        "of",
        "trusted",
        "servers"
      ]
    },
    "MEMPOOL_SERVICES": {
      "API": "https://mempool.space/api/v1/services",
      "ACCELERATIONS": false
    },
    "STRATUM": {
      "ENABLED": false,
      "API": "http://localhost:1234"
    }
  };
}

// Write mempool-config.json before starting PM2
const mempoolConfig = generateMempoolConfig(envConfig, secrets);
const configPath = path.join(BACKEND_DIR, 'mempool-config.json');
try {
  fs.writeFileSync(configPath, JSON.stringify(mempoolConfig, null, 2));
  console.log('✅ Generated mempool-config.json at', configPath);
} catch (error) {
  console.error('❌ Failed to generate mempool-config.json:', error);
}

module.exports = {
  apps: [
    {
      name: 'mempool-backend',
      script: 'dist/index.js',
      cwd: BACKEND_DIR,
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '2G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: path.join(BASE_DIR, 'logs/backend-error.log'),
      out_file: path.join(BASE_DIR, 'logs/backend-out.log'),
      merge_logs: true,
      wait_ready: true,
      listen_timeout: 30000,
      kill_timeout: 5000,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'mempool-frontend',
      script: 'server-simple.js',
      cwd: FRONTEND_DIR,
      instances: 1,
      exec_mode: 'fork',
      env: {
        ...envConfig,
        ...secrets,
        NODE_ENV: 'production',
        PORT: envConfig.FRONTEND_PORT || 4000,
        BACKEND_API: envConfig.BACKEND_API || 'http://127.0.0.1:8999',
        ELECTRS_API: envConfig.ELECTRS_API || 'http://127.0.0.1:3006',
        TRACKER_API: envConfig.TRACKER_API || 'http://127.0.0.1:3000',
      },
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: path.join(BASE_DIR, 'logs/frontend-error.log'),
      out_file: path.join(BASE_DIR, 'logs/frontend-out.log'),
      merge_logs: true,
      wait_ready: false,
      listen_timeout: 10000,
      kill_timeout: 3000,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '5s',
    },
  ],
};
